version: '3.8'
services: 
    codewithvijay:
        image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
        environment: 
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "YOURPASSWORD"
            MSSQL_PID: Express
        ports: 
            - "1433:1433"
    employeeapi:
        build: .
        depends_on: 
            - codewithvijay
        environment: 
            ServerName: "codewithvijay"
            Database: "Employee"
            UserName: "SA"
            Password: "YOURPASSWORD"
        ports: 
            - "80:80"